### ISSUE TITLE
cjpeg: Skip/log already optimized files

### ISSUE THREAD

**Issue by adrianmihalko** [mozilla/mozjpeg#232]
Is there any way to skip and log already optimized files?

**Comment by pornel** [comment]
There is on way to do this, and this probably out of scope of the library. MozJPEG is intended as a very low level library for authors of image compression software.

For example you can use it via [ImageOptim](https://imageoptim.com/mac), which does skip already-optimized images.

Similarly `jpegoptim` can be compiled with mozjpeg instead of libjpeg, and it has an option to skip files too.
