### ISSUE TITLE
Better readme explaining MozJPEG's features

### ISSUE THREAD

**Issue by pornel** [mozilla/mozjpeg#241]
The current readme is very terse and doesn't say much about MozJPEG's features and benefits.

I suggest expanding it with more in-depth description, list of features, example images and links to related articles.

**Comment by DeeDeeG** [comment]
(trying my hand at a general introduction to mozjpeg. This can be refined later or not used, but I'd also like to see a high quality reference for this software, and so I'd like to get the ball rolling.)

To start with, a rundown of all the command-line options (and how they are desirable in common real-world usage scenarios) would be great. I am learning this as I go. My findings for running with no flags: ...

Running it with no flags seems to:

- Make a "progressive" jpg (as opposed to "baseline")

- Run only lossless compression

This makes running without flags useful as a last-step after all other compression steps have been done, regardless of what tool they were done with.

e.g. following up after exporting in a lossy way with GIMP, following up after using Guetzli, etc. etc.

Adding the -fastcrunch flag will make a baseline jpg instead of progressive jpg. 

(Why use baseline vs progressive?: Baseline jpgs anecdotally have been said to be faster/simpler to decode, and said to have have wider support than progressive. Also, baseline jpgs anecdotally have been said to fully render in a browser faster than progressive (according to comments in the Guetzli GitHub issues). On the plus side, progressive jpgs display faster (as a blurry image) even before fully downloaded, if the client supports this, and can usually compress to a smaller size than baseline jpgs. I don't know if every detail I listed here is really true, or if these are all relevant concerns for real world use, just listing some differences I have heard of.)

A section about using quality settings properly would be helpful.

A setting of 95 results in very high quality image, roughly the maximum the lossy encoding operation can produce. Higher than 95 will usually not produce visibly better images, but the file size will be significantly larger.

Lower quality settings can save a significant amount in the file size, whereas artifacts or degradations may in some cases not be noticeable, even down to a quality of 50. There is no quality number that will guarantee an artifact-free image smaller than your input; likewise there is no quality number that will guarantee the best filesize savings and still retain acceptable quality across all images. Around 80 or 85 is usually a safe choice for good savings without extreme artifacts, but your mileage may vary, and selecting a tailored quality setting per-image is encouraged for truly optimal results.

(note: I downloaded a mozjpeg.exe Windows binary, so I don't run jpegtran, or cjpeg, or anything else... just "mozjpeg.exe [flags] [input file]")
