### ISSUE TITLE
Ubuntu 17.04 libpng12.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by maraisr** [mozilla/mozjpeg#255]
**Error message:**

```bash
Module build failed: Error: /home/myApp/node_modules/mozjpeg/vendor/cjpeg:
error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

From [what I can see](https://askubuntu.com/a/895903/250605) I'd need to contact you guys?

----

**OS:** Ubuntu 17.04
**Version:**: mozjpeg v4.1.1

**Package**: `sudo apt-get install libpng-dev` ran with no errors:
```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpng-dev is already the newest version (1.6.28-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
```

> Caveat: mozjpeg is being ran from `image-webpack-loader` out of `webpack`. But believe this issue is more-or-less related to this repo.

**Comment by pornel** [comment]
You have mozjpeg built for a different version of the system (e.g. a Debian one, or for an older version of Ubuntu). You need to recompile it or get a binary compatible with your version of Ubuntu.

**Comment by pedroskakum** [comment]
And how is that done? I'm with the same problem. I do not know how to proceed. Thanks

**Comment by pornel** [comment]
1. Ensure your system's libpng is not misconfigured. This should show `1.6.…` and `-lpng16`:

    ```sh
    pkg-config  --modversion libpng
    pkg-config  --libs libpng
    ```

2. Delete the existing cjpeg binary, and clean build directory (`make clean`)

3. Configure and build again from scratch, following regular build instructions in the repo

**Comment by cosine** [comment]
I just ran into this problem, and the cause is a `cjpeg` Linux binary downloaded by the released versions of this project.  The `cjpeg` binary comes from some configuration specified in `node_modules/mozjpeg/lib/index.js`.

The current workaround is generally to load a copy of `libpng12.so` from a mirrored copy of the older package.

As more and more Linux distributions are updated to no longer include `libpng12.so` in favor of `libpng16.so`, this problem will continue to become more prevalent.

I suggest switching the project to downloading a version of `cjpeg` that staticly links in `libpng12.a` (or whatever newer version desired).

**Comment by kornelski** [comment]
@cosine Just to be clear, we don't release any binaries. You've got a node module made by someone else.
