### ISSUE TITLE
Unexpected file size regression for quality 90

### ISSUE THREAD

**Issue by gradha** [mozilla/mozjpeg#281]
After finding about this project I started testing it but with the images I was trying I wasn't getting the advertised file size savings either with the released tarballs or git head. However, I did find an [osx 3.0 binary](https://github.com/kornelski/mozjpeg/releases) which did reduce jpeg files more than what I was getting with my builds. Wondering if the problem was my OSX machine I set up a debian jessie vm and replicated the unexpected results. Then I started digging through tagged versions and found that file sizes jumped between v3.1 and v.3.2 for files using `-quality 90`. Here are my results:

* [reference.jpg](http://www.elhaso.es/jpg/reference.jpg) 5.2M
* [v3.0.jpg](http://www.elhaso.es/jpg/v3.0.jpg) 1.7M
* [v3.1.jpg](http://www.elhaso.es/jpg/v3.1.jpg) 1.7M
* [v3.2.jpg](http://www.elhaso.es/jpg/v3.2.jpg) 1.9M
* [v3.3.1.jpg](http://www.elhaso.es/jpg/v3.3.1.jpg) 1.9M
* [head.jpg](http://www.elhaso.es/jpg/head.jpg) 1.9M

In this example the size difference doesn't seem great, but for other smaller pictures I've found differences getting from 350KB to 475KB, which in percentage seems much bigger. In general, versions 3.1 and 3.0 generate smaller files than later versions.

Is it ok to stick to using 3.1 or does the size bump change imply some incorrect encoding that was fixed in 3.2+ and which might hurt me in the future? Maybe versions 3.2+ add some metadata like thumbnails which wasn't generated earlier?

**Comment by kornelski** [comment]
This is intentional in the `cjpeg` demo tool. Add `-sample 2x2` to get the old behavior. This does not affect libjpeg library API, which didn't change.

The latest version of the `cjpeg` tool copies approach used in Photoshop and ImageMagick and uses quality to infer the default chroma subsampling setting.

The old version always used chroma subsampling (2x2 AKA 4:2:2) at all quality levels. That lead to rather odd situation where you could have nearly-perfect luma channel with half-resolution chroma channel. Now if you demand high quality, you will also get color at high quality (1x1 AKA 4:4:4).

**Comment by gradha** [comment]
Thanks for the explanation.
