### ISSUE TITLE
PNG 1.6?

### ISSUE THREAD

**Issue by zvezdochiot** [mozilla/mozjpeg#374]
https://github.com/mozilla/mozjpeg/commit/3fed7e016bb2a02a24799acd24030417cf4d6a6d

❓ Mozjpeg in the specified commit is quietly building with libpng 1.2.49. Why specify 1.6 in REQUIRED?

https://github.com/mozilla/mozjpeg/blob/3fed7e016bb2a02a24799acd24030417cf4d6a6d/CMakeLists.txt#L696
https://github.com/mozilla/mozjpeg/blob/3fed7e016bb2a02a24799acd24030417cf4d6a6d/sharedlib/CMakeLists.txt#L97

**Comment by kornelski** [comment]
That's correct. libpng 1.2 is totally unsupported. It's been replaced by libpng 1.4 *10 years ago*. 

I know there are some Linux distros that still have it, but that's because the last 10 years has been a vicious cycle of distros staying on the old version for "maximum compatibility", and developers adding workarounds to support this buggy piece of shit.
