### ISSUE TITLE
Multiple failures when running make test on v4.0.0

### ISSUE THREAD

**Issue by graysky2** [mozilla/mozjpeg#384]
After building [tag v4.0.0](https://github.com/mozilla/mozjpeg/releases/tag/v4.0.0), I ran `make test` and found that 31 of the 151 failed.  Is this expected?  Perhaps I am missing a dependency?

Build system is Arch Linux building in a clean buildroot.
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=/usr/lib \
-DENABLE_STATIC=FALSE -DPNG_SUPPORTED=TRUE -DWITH_JPEG8=TRUE
make
```

* [Log](https://gist.github.com/graysky2/7cc00665fde2a93398d0d9f80a603834) of `cmake` and `make` output.
* [Log](https://gist.github.com/graysky2/76ef4fb44e119b19335ba97a720e1e8b) of `make test` output.

**Comment by kornelski** [comment]
I'm seeing the same failures. These failures are sort-of expected, because the tests come from libjpeg-turbo. They are just md5 hashes of output files, so they are *very* sensitive to the smallest changes of the implementation.

I've checked the results manually, and all the differences that are reported are so tiny they're imperceptible. Probably just rounding errors or some float shenanigans.

I'll just update expected hashes to match the files that are being generated.
